name: Build & Deploy DEV

on:
  push:
    branches: [develop]

permissions:
  contents: read
  id-token: write

jobs:
  build-deploy-dev:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY_DEV }}

      - uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        run: gcloud auth configure-docker europe-north1-docker.pkg.dev

      - name: Build & push image (DEV)
        env:
          PROJECT_ID: dev-openjobseu
          SHA: ${{ github.sha }}
        run: |
          IMAGE=europe-north1-docker.pkg.dev/$PROJECT_ID/$PROJECT_ID/$PROJECT_ID
          docker build -t $IMAGE:$SHA .
          docker push $IMAGE:$SHA

      - name: Deploy to Cloud Run (DEV)
        run: |
          gcloud run services update dev-openjobseu \
            --project dev-openjobseu \
            --region europe-north1 \
            --image europe-north1-docker.pkg.dev/dev-openjobseu/dev-openjobseu/dev-openjobseu:${{ github.sha }}
