name: Build image

permissions:
  contents: read
  id-token: write

on:
  workflow_run:
    workflows: ["Tests"]
    types: [completed]

jobs:

  build-dev:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch != 'main' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY_DEV }}

      - uses: google-github-actions/setup-gcloud@v2


      - name: Debug secret presence
        run: |
          if [ -z "${{ secrets.GCP_SA_KEY_DEV }}" ]; then
            echo "DEV secret is EMPTY"
          else
            echo "DEV secret exists"
          fi


      - name: Configure Docker
        run: gcloud auth configure-docker europe-north1-docker.pkg.dev

      - name: Build & push (DEV)
        env:
          PROJECT_ID: dev-openjobseu
          SHA: ${{ github.event.workflow_run.head_sha }}
        run: |
          IMAGE=europe-north1-docker.pkg.dev/$PROJECT_ID/$PROJECT_ID/$PROJECT_ID

          echo "Pushing to DEV project: $PROJECT_ID"
          docker build -t $IMAGE:$SHA .
          docker push $IMAGE:$SHA


  build-prod:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY_PROD }}

      - uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        run: gcloud auth configure-docker europe-north1-docker.pkg.dev

      - name: Build & push (PROD)
        env:
          PROJECT_ID: openjobseu
          SHA: ${{ github.event.workflow_run.head_sha }}
        run: |
          IMAGE=europe-north1-docker.pkg.dev/$PROJECT_ID/$PROJECT_ID/$PROJECT_ID

          echo "Pushing to PROD project: $PROJECT_ID"
          docker build -t $IMAGE:$SHA .
          docker push $IMAGE:$SHA
