name: terraform-plan

on:
  pull_request:
    paths:
      - "infra/**"

permissions:
  contents: read
  pull-requests: read

jobs:

  plan-dev:
    if: github.base_ref != 'main'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra/gcp/dev

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY_DEV }}

      - run: terraform init -input=false
      - run: terraform validate
      - run: terraform plan -input=false


  plan-prod:
    if: github.base_ref == 'main'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra/gcp/prod

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY_PROD }}

      - run: terraform init -input=false
      - run: terraform validate
      - run: terraform plan -input=false